@startuml

skinparam monochrome true
skinparam shadowing false
skinparam usecaseBackgroundColor transparent

(База Данных) as db
(Запрос названий товаров) as titleBrandQuery
titleBrandQuery -- db : управление


rectangle "Главное окно" {
  (Генеральный запрос) as query
  (Таблица товаров) as productsGrid
}
query -- db : управление
query -- productsGrid : управление


rectangle "Окно товара в магазине"{
  (Поле выбора товара) as products1Field
  (Поле ввода производителя) as producerField
  (Запрос производителей) as producerQuery
  (Поле ответа) as responseText
}
titleBrandQuery --> products1Field : наполнение
products1Field --> producerQuery : изменение
producerQuery -- db : управление
producerField --> producerQuery : изменение
producerQuery --> responseText : Ответ


rectangle "Окно количества телефонов"{
  (Запрос количества товаров) as titleBrandCountQuery
  (Таблица товаров и количества) as titleBrandCountGrid
  (Поле суммы) as costField
}
costField --> titleBrandCountQuery : изменение
titleBrandCountGrid -- titleBrandCountQuery : управление
titleBrandCountQuery -- db : управление

rectangle "Окно поступления товаров" {
  (Запрос цены товаров с даты) as sumQuery
  (Поле ввода даты) as dateField
  (Поле вывода суммы) as sumText
}
dateField --> sumQuery : изменение
db -- sumQuery : управление
sumQuery --> sumText : Заполнение


rectangle "Окно графика поступления товара" {
  (Запрос товара по датам) as titleBrandDateQuery
  (Холст) as canvas
  (Поле выбора товара) as titleBrandField
}
titleBrandQuery --> titleBrandField : наполнение
titleBrandField --> titleBrandDateQuery : изменение
titleBrandDateQuery -- db : управление
titleBrandDateQuery --> canvas : изменение

@enduml
