== Задание 3. Программирование на С++ с использованием классов
=== Часть 3.1. Композиция
Разработать и реализовать диаграмму классов для описанных объектов предметной области, используя механизм композиции. Протестировать все методы каждого класса. Все поля классов должны быть скрытыми (private) или защищенными (protected). Методы не должны содержать операций ввода/вывода, за исключением процедуры, единственной задачей которой является вывод информации об объекте на экран.
Объект – гриб. Поля: название, вес, тип (съедобный, несъедобный, условно съедобный). Методы: процедура инициализации, процедура вывода значений полей на экран и функции, возвращающие значения полей по запросу.
Объект – корзина грибника, в которой лежат грибы. Методы объекта должны позволять: инициализировать объект, добавлять гриб в корзину, убирать гриб из корзины, выводить на экран список собранных грибов с их параметрами и определять, во сколько раз станет легче корзина, если выбросить из нее все несъедобные грибы.
В отчете привести диаграмму разработанных классов и объектную декомпозицию.

=== Часть 3.2. Qt. Полиморфное наследование
Разработать программу, содержащую описание трех графических объектов:
отрезок, равнобедренный треугольник, стрелка компаса (ромб с короткой диагональю).
Реализуя механизм полиморфизма, привести объекты в одновременное вращение вокруг их геометрических центров с различными угловыми скоростями.
В отчете привести диаграмму используемых классов Qt и разработанных классов, граф состояний пользовательского интерфейса и объектную декомпозицию.
