include::attributes-ru.adoc[]

:toc:

<<<


== Введение
*Целью* учебной практики является получение навыков создания небольших программных систем с оконными и консольными интерфейсами.

*Задачами* практики являются:

- более глубокое изучение средств реализации проектов программ на одном из изучаемых универсальных языках программирования высокого уровня;
- овладение методикой и получение практических навыков проектирования небольших программных систем при структурном и объектном подходах;
- воспитание внимания, аккуратности, систематичности, а также формирование интереса к изучаемой профессиональной деятельности.
Выполнение практикума должно способствовать формированию и развитию следующих навыков и умений:
- выделение объектов предметной области, обобщение их в классы, определение связей между классами;
- проектирование эргономичного обеспечения информационных систем;
- разработка и отладка компонентов программных комплексов и систем с помощью современных автоматизированных средств проектирования;
- разработка проектной и эксплуатационной документации на программную и техническую продукцию;
- выполнение контроля разрабатываемых проектов и технической документации на соответствие стандартам и техническим требованиям;
- разработка интерфейсов «человек - ЭВМ».

<<<

:leveloffset: +1

:sectnums:

:imagesdir: ./practice-01/

include::practice-01/README.adoc[]

<<<

:imagesdir: ./practice-02/

include::practice-02/README.adoc[]

<<<

:imagesdir: ./practice-03/

include::practice-03/README.adoc[]

<<<


:leveloffset: -1

:sectnums!:


== Заключение
Во время выполнения учебной практики более глубоко были изучены средства реализации проектов программ на Object Pascal и С++,
получены практические навыки проектирования небольших программных систем при структурном и объектном подходах,
с консольным и графическими интерфейсами.

Кроме этого были получены начальные навыки составления программной документации.
