= Вариант 5
Лабораторная работа 1. Консольные приложения C++ в среде Microsoft Visual Studio
Лабораторная работа выполняется по методическим указаниям.

Лабораторная работа 2. Программирование ввода/вывода и выражений
Вычислить: y= (x2+2ex) * cos(6*z/x - 5)).

Лабораторная работа 3. Основные операторы передачи управления
Найти все простые числа, входящие в диапазон [n,m], где n и m – натуральные числа, n<m. Вывести на экран диапазон и все найденные числа.



== Лабораторная работа 4. Массивы
Задание выдается на занятии преподавателем и выполняется с использованием конспектов лекций.

== Лабораторная работа 5. Использование указателей при работе со строками С++
Известно, что в заданном тексте присутствуют буквы f, r, s. Требуется напечатать символы, непосредственно следующие за первым вхождением каждой из этих букв (всего 3 символа). Пользуясь указателями, выдать на печать адреса этих символов.

== Лабораторная работа 6. Динамические структуры данных. Списки
Дана символьная строка, представляющая собой некоторое длинное целое число. Составить программу, которая вводит строку, организует из цифр введенной строки, преобразованных в целое число, однонаправленный список. Используя сформированный список, подсчитать сумму цифр введенного числа и количество повторений каждой цифры. Вывести на печать сформированный список, найденную сумму и количество повторений цифр в виде таблицы.

== Лабораторная работа 7. Простые объекты
Описать класс, включающий заданные поля и методы, двумя способами: без конструктора и с конструктором. Протестировать все методы класса. Поля класса должны быть скрытыми (private) или защищенными (protected). Методы не должны содержать операций ввода/вывода, за исключением процедуры, единственной задачей которой является вывод информации об объекте на экран.
Объект – звезда. Поля: название, температура в кельвинах. Методы: инициализирующая процедура, процедура вывода на экран значений полей и функция, определяющая цвет звезды по ее температуре.
В отчете привести диаграмму разработанных классов и объектную декомпозицию.

== Лабораторная работа 8. Наследование
Разработать и реализовать иерархию классов для описанных объектов предметной области, используя механизмы наследования. Протестировать все методы каждого класса. Все поля классов должны быть скрытыми (private) или защищенными (protected). Методы не должны содержать операций ввода/вывода, за исключением процедуры, единственной задачей которой является вывод информации об объекте на экран.
Объект – прямоугольник. Поля: длина, ширина. Методы: процедура инициализации, процедура вывода значений полей на экран, функция вычисления площади.
Объект – картинная рама. Поля: длина и ширина внутренней части рамы, ширина багета (расстояние между внутренним и внешним краем рамы). Методы: процедура инициализации, процедура вывода значений полей на экран, функция определения максимальной площади картины, которая уместится в раму, и процедура определения полной длины и ширины картины с рамой.
В отчете привести диаграмму разработанных классов и объектную декомпозицию.

== Лабораторная работа 9. Программирование с использованием Qt
Лабораторная работа выполняется по методическим указаниям.

== Лабораторная работа 10. Qt. Создание контейнеров
Моделировать дек, в качестве элементов которого могут использоваться целые числа и слова. Операции: добавление элемента, удаление элемента, печать элементов. При добавлении и удалении элементов выбирать сторону дека: начало или конец. Создать класс-потомок, который содержит функцию сортировки элементов (числа по возрастанию, слова по алфавиту). Тестировать полученную модель.
Разработать собственную иерархию классов, готовые контейнеры Qt не использовать. Пользовательский интерфейс для работы с моделью реализовать на Qt. В отчете представить диаграмму классов и обосновать выбранную структуру представления данных.
