include::exam-attrs.adoc[]
:ticket-number: ____

include::header.part.adoc[]


== Задание 2. Простое и множественное наследование классов. Пример
*Простое наследование* -- механизм расширения функционала класса через дополнение участников класса.

При конструировании сначала вызывается конструктор родителя, потом конструктор потомка.
Если конструктор родителя требует параметров, то потомок обязан иметь объявление конструктора.

Для реализации общего доступа к полям между родителем и потомком используется `protected` и `public` модификаторы доступа, так как к `private` полям родителя будет иметь доступ только родитель.
Также возможно ограничение прав доступа извне к полям родителя при указании наследования.
Для реализации перезаписываемых полей, или полей, которые родитель требует для работы, но сам не определяет используется модификатор `virtual`.

*Множественное наследование* -- механизм расширения функционала с использованием нескольких базовых классов.

Для избежания проблем при двойном наследовании родители должны объявлять доступные потомкам поля как `virtual`.

.Примеры использования наследования
[plantuml]
....
Log <|-- Plow

Human <|-- Cyborg
Robot <|-- Cyborg


class Clickable {
  bool equals(const Button &another);
}
class Rect {
  bool equals(const Rect &another);
}
class Object {
  virtual bool equals(const Rect &another)
}

Clickable <|-- Button
Rect <|-- Button
Object <|-- Rect
Object <|-- Clickable
....
