= Создание простейших HTML-страниц, Элементы семантической разметки. Валидаторы кода
:lab: 1

== Задание 1

[cols=2,frame=no,grid=no]
|===
a|
.lorem.html
[source,html]
----
include::lorem.html[]
----

|
Выполните разметку HTML-страницы с использованием элементов семантической разметки текста.
Напишите не менее 10 строк произвольного текста.
Выделите в каждой строке несколько слов как более важные, значительно важные, добавьте математические формулы и пр.
Также, с использованием семантической разметки, добавьте к тексту произвольные строки кода на любом языке программирования.

Подготовьте второй вариант разметки, отличающийся выделенными словами.
Замените фрагменты, которые ранее отображались курсивом на фрагменты, отображаемые жирным шрифтом.
|===


<<<


== Задание 2

[cols=2,frame=no,grid=no]
|===
a|
.schedule.html
[source,html]
----
include::schedule.html[]
----

a|
Сформируйте HTML-страницу с фрагментом расписания занятий (используйте элемент table).
Выберите фрагмент расписания таким образом, чтобы хотя бы в одном месте возникала необходимость объединения ячеек таблицы.
|===


<<<


== Задание 3

[cols=2,frame=no,grid=no]
|===
a|
.form.html
[source,html]
----
include::form.html[]
----

a|
Подготовьте разметку формы регистрации на произвольном сайте.
Для расположения элементов используйте табличную верстку.
|===

== Задание 4

Используя валидаторы HTML (предустановленный в браузере или https://validator.w3.org/), проверьте полученные HTML-страницы на наличие ошибок.
Составьте таблицу выявленных ошибок, в которую внесите все ошибки валидации и их фактические проявления в браузере.
Устраните все найденные ошибки.

=== Решение

Ошибок валидации с validator.w3.org не найдено.
