= Классы, модули, примеси
:lab:

== Часть 1
Сформировать программным путем файл F, компоненты которого являются целыми числами.
Получить файл G, образованный из файла F исключением повторных вхождений одного и того же числа.

Автоматический тест программы обязательно должен проверять работу с файлами.
=== Решение

.logic.rb
[source,ruby]
----
include::p1/logic.rb[]
----

.cli.rb
[source,ruby]
----
include::p1/cli.rb[]
----

.test.rb
[source,ruby]
----
include::p1/test.rb[]
----

== Часть 2

Разработать и реализовать иерархию классов для описанных объектов предметной области,
используя механизмы наследования. Проверить ее на тестовом примере,
с демонстрацией всех возможностей разработанных классов на конкретных данных.

Объект — Треугольник, заданный точками на плоскости. Объект умеет выводить на экран
значение своих полей и отвечать на запрос об этих значениях и вычислять площадь фигуры.

Объект — Треугольная призма. Объект умеет выводить на экран содержимое своих полей,
возвращать по запросу их значения и площадь развертки.

В тестирующей программе обеспечить автоматическую проверку того,
что созданные объекты действительно соответствют заданной иерархии классов.

=== Решение


.logic.rb
[source,ruby]
----
include::p2/logic.rb[]
----

.cli.rb
[source,ruby]
----
include::p2/cli.rb[]
----

.test.rb
[source,ruby]
----
include::p2/test.rb[]
----

Reek ошибок не выдаёт.

== Вывод
Были получены практические навыки использования классов и работы с файлами.
