== Задача
Решить задачу, используя процедуру или функцию. Выбор обосновать. На примере полученной программы продемонстрировать умение:

. назначать точку останова;
. выполнить программу по шагам с заходом в процедуры и без захода;
. определять значения переменных на конкретном шаге.

Дана целочисленная матрица A(n,m), n,m ≤ 10. Преобразовать ее, упорядочив каждую строку по неубыванию элементов.

[cols=2,grid=no,frame=no]
|===
a|
.Код основной программы
[source,pascal]
----
include::07.pas[]
----

a|
.Sorting.pas
[source,pascal]
----
include::Sorting.pas[]
----

|===


.Тестирование
[%header, cols=3*, frame=no]
|===
|Ввод |Результат |Ожидается

a|
----
2 3
1 5 9 7 5 3
----
a|
----
   1   5   9
   5   3   7
----
a|
----
1 5 9
5 3 7
----

a|
----
3 3
1 5 9 7 5 3 1 3 2
----
a|
----
   1   5   9
   5   3   7
   1   2   3
----
a|
----
1 5 9
3 5 7
1 2 3
----
|===

== Вывод
Для операции сортирвки массива, особенно частичной сортировки, лучше всего использовать процедуры, так как происходит изменение исходного массива. При использовании функций надо создавать новый массив и возвращать его в качестве результата.

Так же я получил опыт отладки программ в среде Lazarus.
