== Лабораторная работа 8. Наследование
Разработать и реализовать иерархию классов для описанных объектов предметной области, используя механизмы наследования. Протестировать все методы каждого класса. Все поля классов должны быть скрытыми (private) или защищенными (protected). Методы не должны содержать операций ввода/вывода, за исключением процедуры, единственной задачей которой является вывод информации об объекте на экран.
Объект – прямоугольник. Поля: длина, ширина. Методы: процедура инициализации, процедура вывода значений полей на экран, функция вычисления площади.
Объект – картинная рама. Поля: длина и ширина внутренней части рамы, ширина багета (расстояние между внутренним и внешним краем рамы). Методы: процедура инициализации, процедура вывода значений полей на экран, функция определения максимальной площади картины, которая уместится в раму, и процедура определения полной длины и ширины картины с рамой.
В отчете привести диаграмму разработанных классов и объектную декомпозицию.

