== Лабораторная работа 8. Наследование
Разработать и реализовать иерархию классов для описанных объектов предметной области, используя механизмы наследования. Протестировать все методы каждого класса. Все поля классов должны быть скрытыми (private) или защищенными (protected). Методы не должны содержать операций ввода/вывода, за исключением процедуры, единственной задачей которой является вывод информации об объекте на экран.

Объект – прямоугольник. Поля: длина, ширина. Методы: процедура инициализации, процедура вывода значений полей на экран, функция вычисления площади.

Объект – картинная рама. Поля: длина и ширина внутренней части рамы, ширина багета (расстояние между внутренним и внешним краем рамы). Методы: процедура инициализации, процедура вывода значений полей на экран, функция определения максимальной площади картины, которая уместится в раму, и процедура определения полной длины и ширины картины с рамой.

В отчете привести диаграмму разработанных классов и объектную декомпозицию.


.Диаграмма классов
[plantuml]
....
skinparam classBackgroundColor transparent
skinparam shadowing false
skinparam monochrome true
skinparam linetype polyline

class Rect {
    #int width, height;

    +Rect(int a, int b);

    +int getArea();
    +void print();
}

class Frame  {
    -int gut;

    +Frame(int w, int h, int g);

    +std::tuple<int, int> getFullSize();
    +void print();
}

Rect <|- Frame

....

.Объектная декомпозиция
[plantuml]
....
skinparam classBackgroundColor transparent
skinparam shadowing false
skinparam monochrome true

(Рамка) as frame
(Прямоугольник) as rect
Программист as usr
(Консоль) as console

usr --> frame : Инициализация
usr --> rect : Инициализация

rect --> console : Вывод данных
frame --> console : Вывод данных
....

[frame=no,grid=no,cols=2]
|===
a|
.Код тестирующей программы
[source,cpp]
----
include::main.cpp[]
----

a|
.Результат работы тестирующей программы
----
1
10x20
11
20x10 5
----
|===

**Вывод**: Я научился работать с наследованием объектов в C++.
