= Таблицы стилей. Селекторы. Блочная модель разметки. Страница с кнопками и ссылками
:lab: 2


== Задача

. Подготовьте разметку произвольного текста, содержащего не менее 10 строк (могут быть использованы материалы из лабораторной работы No 1) с использованием таблицы стилей. Продемонстрируйте выделение отдельных слов с помощью стилей, цвета и шрифта.
. С использованием элементов div подготовьте разметку таблицы, например, содержащей фрагмент расписания.
. Возьмите шаблон страницы Bootstrap (см. Приложение Б методического пособия). Измените цвет фона навигационной панели и подвала сайта на свое усмотрение.
. Вставьте:
.. место текста “Вставьте сюда форму” форму из лабораторной работы 1;
.. на место текста “Вставьте сюда таблицу” произвольную таблицу (на основе элементов table/tr/td);
.. на место текста “Вставьте сюда текст” блок разметки текста (из пункта 1).
. Добавьте классы Bootstrap в элементы формы, и заголовки таблицы.
. Проверьте полученные HTML-страницы на наличие ошибок. Составьте таблицу выявленных ошибок, в которую внесите все ошибки валидации и их фактические проявления в браузере. Устраните все найденные ошибки.


== Решение

.index.html
[source,html]
----
include::index.html[]
----


Ошибок валидации нет.
