= Задание 2. Создание программной системы с элементарным интерфейсом консольного режима С++

Выполнить структурную декомпозицию, разработать структурную схему, содержащую не менее 3 подпрограмм, и алгоритмы этих подпрограмм.
Реализовать на С++ в консольном режиме.
Предусмотреть примитивный интерфейс типа меню, позволяющий выбирать нужную подпрограмму.

Разработать программу, которая реализует операции над комплексными числами.

Реализовать следующие операции:

. ввод чисел
. суммирование
. вычитание
. умножение на скаляр
. вывод результатов операций на экран


== Анализ задания

Для предоставления более удобного интерфейса для программиста математические операции стоит реализовать перегрузкой стандартных математических операторов `+`, `-` и `*` для комплексных чисел.
А умножение на скаляр будет частным случаем умножения на комплексное число с мнимой частью, равной нулю.
Для вывода чисел стоит использовать стандартный для библиотеки `std` механизм -- оператор `<<` и реализацию `std::ostream` для него.
Функицонал ввода комплексных чисел стоит вынести из реализации класса в основную программу.
Инициализацию чисел проводить через конструктор класса.

== Схемы и таблицы

.Схема синтаксиса ввода-вывода чисел
----
number := <real>[, <img>]
real := [-]<decimal>
img := [-]<decimal>
----

.Схема пути пользователя в интерфейсе
[plantuml]
....
skinparam monochrome true
skinparam shadowing false

(*) -> "Ввод первого числа"
-> "Ввод второго числа"
-> "Выбор оператора"
-> "Вывод результата"
-> (*)
....

.Диаграмма классов
[plantuml]
....
skinparam classBackgroundColor transparent
skinparam shadowing false
skinparam monochrome true
skinparam linetype polyline

set namespaceSeparator ::

class std::ostream

class ComplexNumber {
    -float real
    -float i

    +ComplexNumber operator+(const ComplexNumber &left, const ComplexNumber &right);
    +ComplexNumber operator-(const ComplexNumber &left, const ComplexNumber &right)
    +ComplexNumber operator*(const ComplexNumber &left, const ComplexNumber &right)
    +std::ostream &operator<<(std::ostream &os, const ComplexNumber &me)
}

std::ostream <.. ComplexNumber

....

.Структурная декомпозиция программы
[plantuml]
....
skinparam classBackgroundColor transparent
skinparam shadowing false
skinparam monochrome true

usecase "Main programm" as main
usecase "Parser producer" as parse

rectangle ComplexNumber {
  usecase "Add (+)" as add
  usecase "Minus (-)" as min
  usecase "Multiply (*)" as mul
  usecase "Print (<<)" as print
}

main --> parse
main --> add
main --> min
main --> mul
main --> print
....

<<<

== Реализация

.Код реализации основной программы. main.cpp
[source, cpp]
----
include::main.cpp[]
----

.Заголовочный файл класса ComplexNumber.h
[source,cpp]
----
include::ComplexNumber.h[]
----

.Код реализации методов класса
[source,cpp]
----
include::ComplexNumber.cpp[]
----

.Пример работы программы
[source]
----
Format of complex numbers: <real>[,<imagine>]

Enter first number:
1,0.5
Enter second number:
12,-4
Enter operator (+, -, *):
+
Result: 13, -3.5
----

== Вывод
Я научился реализовывать классы в C++, а так же простейшие последовательные консольные пользовательские интерфейсы.
Также я попрактиковался в реализации простейших операций с комплексными числами.
